### ISSUE TITLE
今日校园版本过低，请更新至最新版本！

### ISSUE THREAD

**Issue by vintingb** [Starix610/gdou-tools#10]
{"code":"4","message":"今日校园版本过低，请更新至最新版本！","datas":null}
猜测是在最后一步签到的时候，生成的Cpdaily - Extension所导致，尝试修改creatExtention中的appVersion不成功

**Comment by Starix610** [comment]
> {"code":"4","message":"今日校园版本过低，请更新至最新版本！","datas":null}
> 猜测是在最后一步签到的时候，生成的Cpdaily - Extension所导致，尝试修改creatExtention中的appVersion不成功

应该不是这个导致，appVersion参数一般来说不影响，我在4个月之前测试过。出现这个提示的原因应该是DES加密生成的Cpdaily - Extension有误，5月份开始我就下线这个功能了不再更新了，猜测过了这么久今日校园可能更新了DES加密的密钥和参数，需要重新逆向app来获取新密钥（我这个版本的密钥是当时取了一个大佬逆向后的结果，非自己逆向得到的）
