### ISSUE TITLE
关于cpdaily-extention

### ISSUE THREAD

**Issue by OrionAAAA** [Starix610/gdou-tools#2]
请问大佬extention的加密方法是如何破解的呢。你是把app逆向了吗

**Comment by Starix610** [comment]
> 请问大佬extention的加密方法是如何破解的呢。你是把app逆向了吗

不是我逆向的，是一个大佬在之前把app逆向了，找到了加密算法，我是用了他提供的加密方法和密钥。不过现在今日校园好像进行安全加固了，逆向恐怕不是那么容易了，不过它的加密算法和密钥还没变。

**Comment by OrionAAAA** [comment]
那，我能借用一下那段加密的代码吗

**Comment by Starix610** [comment]
> 那，我能借用一下那段加密的代码吗

可以呀，开源的

**Comment by OrionAAAA** [comment]
感谢！
